services:
  siem-node:
    build: .
    container_name: siem-node
    privileged: true
    pid: host
    network_mode: host
    volumes:
      - /opt/siem/config:/app/config  
      - /opt/siem/logs:/app/logs      

    environment:
      - SIEM_SERVER_URL=http://10.144.121.140:8000/log
      - SIEM_SETTINGS_URL=http://10.144.121.140:8000/api/nodes/{}/settings
      - SIEM_API_KEY=secretkey
    stdin_open: true
    tty: true