name: Build and Push SIEM Node

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log into GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/siem-node:latest ./siem_node
      
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/siem-node:latest

      - name: Cleanup old images
        uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: user         
          token: ${{ secrets.PAT_TOKEN }}
          repository-owner: ${{ github.repository_owner }}
          repository-name: siem-node
          delete-untagged: true
          keep-at-most: 5
